//Error First Callback
//como convencion cuando se llama a un callback, es pasar el error como primer argumento

function asincrona(callback) {
	setTimeout(()=> {
		try {
			let a = 3 + z; //va a dar error, es el objetivo del ejemplo üòèüòè
			callback(null, a);
		} catch(error) {
			callback(error) //podr√≠a pasarse como segundo argumento un null
		}
	}, 1000)
}

asincrona((error, dato)=> {
	if(error) {
		console.error('tenemos un error', error);
		// throw error; no va a funcionar porque estamos dentro una de una funci√≥n asincrona
		return false; //con esto paramos la ejecuci√≥n de la funcion
	}
	console.log('todo sali√≥ bien! mi dato es: ', dato)
});